### ISSUE TITLE
[Suggestion] Config to only allow picking with empty main hand

### ISSUE THREAD

**Issue by thimblebird** [QinomeD/Gentle-Picking#1]
title 🐢 or make it the standard without adding a config (would also fix https://github.com/QinomeD/Gentle-Picking/issues/2 possibly)

**Comment by QinomeD** [comment]
I'll look into it later.

**Comment by QinomeD** [comment]
Fixed

**Comment by QinomeD** [comment]
Will add to cf in a moment, ofc remember that you have to wait krillion years for approval /j

**Comment by QinomeD** [comment]
nvm it was pretty fast

**Comment by thimblebird** [comment]
yeah, it's a gamble i know :D ty 💚🐢
